export const chandraImages = [
  { key: 0, path: '/Gallery/under-construction/Chandra/1_OYVoNgsomC.jpg' },
  { key: 1, path: '/Gallery/under-construction/Chandra/2_z2DGAt3COZ.jpg' },
  { key: 2, path: '/Gallery/under-construction/Chandra/3_SSUdPJVP-2.jpg' },
  { key: 3, path: '/Gallery/under-construction/Chandra/4_bibkU5aKe8.jpg' },
  { key: 4, path: '/Gallery/under-construction/Chandra/5__X6zDgdXWZ.jpg' },
  { key: 5, path: '/Gallery/under-construction/Chandra/6_THgCrQwpF_.jpg' },
  { key: 6, path: '/Gallery/under-construction/Chandra/7_uarnTmeRu.jpg' },
  { key: 7, path: '/Gallery/under-construction/Chandra/8_1eHt3LsAu.jpg' },
  { key: 8, path: '/Gallery/under-construction/Chandra/10_RLVm-u0taM.jpg' },
  { key: 9, path: '/Gallery/under-construction/Chandra/20_3w9rlIkmPx.jpg' },
  { key: 10, path: '/Gallery/under-construction/Chandra/11_YIHqGMKyqW.jpg' },
  { key: 11, path: '/Gallery/under-construction/Chandra/12_7EG_A0kkO9.jpg' },
  { key: 12, path: '/Gallery/under-construction/Chandra/13_TIj_6RZzYi.jpg' },
  { key: 13, path: '/Gallery/under-construction/Chandra/14_SEP0RZRxC.jpg' },
  { key: 14, path: '/Gallery/under-construction/Chandra/15_mtn0dV1Zq6.jpg' },
  { key: 15, path: '/Gallery/under-construction/Chandra/16_Uk6rCCeJEM.jpg' },
  { key: 16, path: '/Gallery/under-construction/Chandra/17_4LvAJ9pEZ.jpg' },
  { key: 17, path: '/Gallery/under-construction/Chandra/18_JqFJKjUsl.jpg' },
  { key: 18, path: '/Gallery/under-construction/Chandra/19_W2nyzgQvFT.jpg' },
];

export const suryaImages = [
  { key: 0, path: '/Gallery/Completed/1_Z2-YuXbmaj.jpg' },
  { key: 1, path: '/Gallery/Completed/2_0G-J5vSHPS.jpg' },
  { key: 2, path: '/Gallery/Completed/3_8nhFaOC6Ae.jpg' },
  { key: 3, path: '/Gallery/Completed/4_A9_3I2zsR.jpg' },
  { key: 4, path: '/Gallery/Completed/5_ZbmHY1s6zs.jpg' },
  { key: 5, path: '/Gallery/Completed/6_RlzcL3sMah.jpg' },
  { key: 6, path: '/Gallery/Completed/7_yGLlH8ZaM.jpg' },
  { key: 7, path: '/Gallery/Completed/8_WKYrZma8G.jpg' },
  { key: 8, path: '/Gallery/Completed/9_T-5Ua1Rg6t.jpg' },
  { key: 9, path: '/Gallery/Completed/10_iBl0-OG3It.jpg' },
  { key: 10, path: '/Gallery/Completed/11_LPZKculhj9.jpg' },
  { key: 11, path: '/Gallery/Completed/12_Ek45sqyEQ.jpg' },
  { key: 12, path: '/Gallery/Completed/13_HjhXxmtQY.jpg' },
  { key: 13, path: '/Gallery/Completed/14_4tPLVRoxAr.jpg' },
  { key: 14, path: '/Gallery/Completed/15_GPpSQ2gMX.jpg' },
  { key: 15, path: '/Gallery/Completed/16_tXfefMdtE.jpg' },
  { key: 16, path: '/Gallery/Completed/17_SQWp4aL7p.jpg' },
  { key: 17, path: '/Gallery/Completed/18_9qpADgXtf.jpg' },
  { key: 18, path: '/Gallery/Completed/19_F2MWS30IX.jpg' },
  { key: 19, path: '/Gallery/Completed/20_rI9lL1zoN.jpg' },
  { key: 20, path: '/Gallery/Completed/21_opUBdhx3y.jpg' },
  { key: 21, path: '/Gallery/Completed/22_F5Rm69VLr.jpg' },
];

export const viewsImages = [
  //{ key: 1, path: '/Gallery/Views/2_nab70nffM.jpg' },
  { key: 2, path: '/Gallery/Views/3_Az2kDo7f_d.jpg' },
  { key: 3, path: '/Gallery/Views/5_nORAe1_lv.jpg' },
  { key: 4, path: '/Gallery/Views/6_RUnMTxIbQ.jpg' },
  { key: 5, path: '/Gallery/Views/7_lsPB4beRYp.jpg' },
  { key: 6, path: '/Gallery/Views/8_i6Ia3gcGHT.jpg' },
  { key: 7, path: '/Gallery/Views/9_kukrsV7WYi.jpg' },
  { key: 8, path: '/Gallery/Views/10_wx0UJ16_S8.jpg' },
  { key: 9, path: '/Gallery/Views/14__ZzTLyFuI.jpg' },
  { key: 10, path: '/Gallery/Views/15_5c0-NbpO6i.jpg' },
  { key: 11, path: '/Gallery/Views/16_wm1TsmnyA.jpg' },
  { key: 12, path: '/Gallery/Views/17_CboXZsbHe.jpg' },
  { key: 13, path: '/Gallery/Views/18_PyZ7ps04Zd.jpg' },
  { key: 14, path: '/Gallery/Views/19_HANC59WD_.jpg' },
  { key: 15, path: '/Gallery/Views/20_W84DaS4xWY.jpg' },
  { key: 16, path: '/Gallery/Views/21_al98srg90.jpg' },
  { key: 17, path: '/Gallery/Views/22_Y43L9snhZ.jpg' },
  { key: 18, path: '/Gallery/Views/23_V18EiaOvm.jpg' },
  { key: 19, path: '/Gallery/Views/24_9C2VQyyUV.jpg' },
  { key: 20, path: '/Gallery/Views/25_7Wr_YaXKg.jpg' },
  { key: 21, path: '/Gallery/Views/26_E4yYhcka8.jpg' },
  { key: 22, path: '/Gallery/Views/27_epDVW5gV4y.jpg' },
  { key: 23, path: '/Gallery/Views/28_w3NmA8syi-.jpg' },
];

export const jalaImages = [
  { key: 1, path: '/Gallery/under-construction/Jala/1_F1SJLpvViM.jpg' },
  { key: 2, path: '/Gallery/under-construction/Jala/2_YIeWz0J_pw.jpg' },
  { key: 3, path: '/Gallery/under-construction/Jala/3_d1EimqTpW.jpg' },
  { key: 4, path: '/Gallery/under-construction/Jala/4_G6H4RZfjw.jpg' },
  { key: 5, path: '/Gallery/under-construction/Jala/5_Gp1dVmb81r.jpg' },
  { key: 6, path: '/Gallery/under-construction/Jala/6_bH5jEKi0Wf.jpg' },
  { key: 7, path: '/Gallery/under-construction/Jala/7_pGbrQHEZMU.jpg' },
  { key: 8, path: '/Gallery/under-construction/Jala/8_r9dhLOVTEP.jpg' },
  { key: 9, path: '/Gallery/under-construction/Jala/9_asv647_QfR.jpg' },
];
